### ISSUE TITLE
Build crashes with "wrong argument formatting! too many arguments"

### ISSUE THREAD

**Issue by LeeReid1** [korbinian90/ROMEO#18]
I've followed the build instructions in the related repo. After a fairly long build process, what I presume is a test is run:

```
./romeo/bin/romeo /some/path/to/romeo/julia-packages/dev/CompileMRI/test/data/small/Phase.nii -o /tmp/jl_OnIrwFyvaj -t 1:3 -k nomask
```

This results in 

```
wrong argument formatting!
too many arguments
```

Causing the build (test?) process to abort.

The issue is that there is no `-p` flag placed before the filename

**Comment by korbinian90** [comment]
Thank you for reporting this, I recently changed a few things and must have messed up something in the process.
I will investigate it, but it might take some time until I get to it.

Here is an alternative way of running the same ROMEO cmd interface, without needing to compile anything: https://github.com/korbinian90/ROMEO.jl#usage---command-line
I think there should be no disadvantages compared to the compiled version. I plan to suggest this as the new default method, since compilation is not yet officially supported by julia and causes problems from time to time.

**Comment by korbinian90** [comment]
It seems like another "big" issue with the compilation approach might be the CUDA support. One of the packages (clearswi) got support for QSM on GPUs, and this makes the package compiler include the whole 1.6GB CUDA_Runtime library.

In any case, I changed the romeo test and added the -p flag like you suggested. Thanks again!

**Comment by korbinian90** [comment]
This should be resolved now. Please open again, if the issue remains
