### ISSUE TITLE
Unpublished version is the only one that works for my data

### ISSUE THREAD

**Issue by akarsa** [korbinian90/ROMEO#7]
Hi,

Our group has been using ROMEO in an MS clinical study for QSM phase unwrapping and it usually works well. However, for a handful of subjects, all the currently downloadable versions leave some residual wraps in the total field map. Interestingly, I got another version ages ago from Barbara Dymerska (called ROMEO_20200130_compiled_win) which works perfectly even in these cases. We have contacted Barbara and she advised that "it looks like some voxel close to the sinuses acts as a tipping point: it may still have relatively high quality value in the quality map and in one case algorithm goes through this voxel slightly earlier than in the other case. The difference can be as small as just slightly different numerical approximation. But it’s worth checking if there is a slight difference in ROMEO weights between this version and the next one." She also suggested that we check the newest version with -k nomask as there was a bug in some of the earlier versions resulting in no mask being used even when -k robustmask was set. We have tried every masking option across a handful of versions without success. We could just continue using ROMEO_20200130_compiled_win, but some of the processing will have to be done on Linux (for other studies as well). Is there any way to figure out what that early version did differently and how we could set up the newest version in the same way?

Many thanks,
Anita

**Comment by korbinian90** [comment]
Hi Anita,

Thanks for the interest in ROMEO and your feedback.
I looked in the git commit from 28.1.2020, which should match your old version. We had 2 additional magnitude weights in that version, one of them tried to avoid artefacts with high magnitude intensity. We did remove those weights when we tried to reduce the complexity for publication and we couldn't find a case where those were beneficial. There was also a change how the weights are multiplied.

It is easy to add those two weights back in and make them optional. I try to do that soon. I hope that this will solve your problem, otherwise I would need a dataset to find out what causes the difference.

Cheers,
Korbinian

**Comment by akarsa** [comment]
Hi Korbinian,

Thank you for your quick reply!

We would be very interested to try a new version where the additional magnitude weights could be used! We would also immediately test it in two different clinical studies. We are also happy to share some images with you if that helps.

Many thanks and best wishes,
Anita

**Comment by korbinian90** [comment]
Hi Anita,

I compiled the new version 3.2.5, which includes two additional magnitude weights. They can be selected via `--weights 111111` (This activates all 6 weights). These are six 0 or 1 values. The first four weights are the standard ROMEO weights and the last two digits are to select the new weights. If this doesn't help to fix your problem, you can send me a link to a sample dataset to korbinian90@gmail.com.

Cheers,
Korbinian

**Comment by akarsa** [comment]
Thank you so much!
